create table if not exists public.uzzapbot_ai_events (
  id bigint generated by default as identity primary key,
  room_name text not null,
  event_type text not null,
  dry_run boolean not null default true,
  topic text,
  confidence double precision,
  action text,
  game text,
  allowed boolean,
  reason text,
  response text,
  input_chars integer,
  created_at timestamptz not null default now()
);
alter table public.uzzapbot_ai_events enable row level security;
revoke all on public.uzzapbot_ai_events from anon, authenticated, public;
grant select, insert, update, delete on public.uzzapbot_ai_events to service_role;